version: '3'
services:
 backenderp:
  container_name: backenderp
  build: ./backend
  volumes:
    - .:/backend

 frontenderp:
  container_name: frontenderp
  build: ./frontend
  depends_on:
    - backenderp
  links:
    - backenderp
  volumes:
    - .:/frontend
  ports:
    - "5000:5000"
  
